server:
  port: 9001
spring:
  application:
    name: express-server
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/express?allowPublicKeyRetrieval=true&socketTimeout=10000&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&useSSL=false&createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    use-column-label: true
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
netty:
  host: localhost
  port: 7397
token:
  secret: "123456"
  expire: 24
wx:
  access-token: https://api.weixin.qq.com/sns/oauth2/access_token?appid=${wx.app-id}&secret=${wx.app-secret}&code=%s&grant_type=authorization_code
  app-id: wxac76296eea62f17a
  app-secret: c39e1b4a0b3ef2b84d4ac09522dd7dbc
  authorize: https://open.weixin.qq.com/connect/qrconnect?appid=${wx.app-id}&redirect_uri=%s&response_type=code&scope=snsapi_login&state=%s#wechat_redirect
  bind-callback: /manager/sop/user/callback/wx/bind
  login-callback: /manager/sop/user/callback/wx/login
  redirect-uri: https://ops.championlang.com/
  unbind-callback: /manager/sop/user/callback/wx/unbind
  userinfo: https://api.weixin.qq.com/sns/userinfo?access_token=%s&openid=%s
